app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
