AddCar:
    path:   /add/car
    controller: App\Controller\AddCarController::form
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

CarEdit:
    path:   /car/edit/{id}
    controller: App\Controller\CarEditController::form
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

Form:
    path:   /form
    controller: App\Controller\FormController::form
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

Cars:
    path:   /car/list
    controller: App\Controller\CarListController::listView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

CarDetail:
    path:   /car/detail/{id}
    controller: App\Controller\CarDetailController::detailView
    defaults:
      _format: html
    requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
